import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type InvoiceData = {
  id: string;
  customer_name: string;
  customer_email?: string;
  customer_phone?: string;
  amount: number;
  description?: string;
  status: string;
  due_date: string;
  created_at: string;
  business_name?: string;
  business_email?: string;
  currency?: string;
};

export function generateInvoicePDF(invoice: InvoiceData) {
  const doc = new jsPDF();
  const currencySymbol = invoice.currency === "USD" ? "$" : invoice.currency === "GBP" ? "£" : "₦";

  // Header background
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, 210, 40, "F");

  // Logo / Brand
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("RISELY", 14, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Your AI Business Operating System", 14, 26);
  doc.text("userisely.com", 14, 33);

  // Invoice label top right
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 196, 20, { align: "right" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`#INV-${invoice.id.slice(0, 8).toUpperCase()}`, 196, 30, { align: "right" });

  // Reset text color
  doc.setTextColor(30, 30, 30);

  // Invoice details section
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("BILL TO", 14, 55);
  doc.setFont("helvetica", "normal");
  doc.text(invoice.customer_name, 14, 62);
  if (invoice.customer_email) doc.text(invoice.customer_email, 14, 68);
  if (invoice.customer_phone) doc.text(invoice.customer_phone, 14, 74);

  // Invoice meta right side
  doc.setFont("helvetica", "bold");
  doc.text("Invoice Date:", 130, 55);
  doc.text("Due Date:", 130, 62);
  doc.text("Status:", 130, 69);

  doc.setFont("helvetica", "normal");
  doc.text(new Date(invoice.created_at).toLocaleDateString(), 175, 55, { align: "right" });
  doc.text(new Date(invoice.due_date).toLocaleDateString(), 175, 62, { align: "right" });

  // Status badge color
  const statusColor = invoice.status === "paid" ? [22, 163, 74] :
    invoice.status === "overdue" ? [220, 38, 38] : [202, 138, 4];
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.setFont("helvetica", "bold");
  doc.text(invoice.status.toUpperCase(), 175, 69, { align: "right" });
  doc.setTextColor(30, 30, 30);

  // From business
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, 88);
  doc.setFont("helvetica", "normal");
  doc.text(invoice.business_name || "My Business", 14, 95);
  if (invoice.business_email) doc.text(invoice.business_email, 14, 101);

  // Items table
  autoTable(doc, {
    startY: 115,
    head: [["Description", "Amount"]],
    body: [
      [
        invoice.description || "Professional Services",
        `${currencySymbol}${invoice.amount.toLocaleString()}`
      ]
    ],
    foot: [
      ["Subtotal", `${currencySymbol}${invoice.amount.toLocaleString()}`],
      ["Tax (0%)", `${currencySymbol}0`],
      ["TOTAL", `${currencySymbol}${invoice.amount.toLocaleString()}`],
    ],
    headStyles: {
      fillColor: [124, 58, 237],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    footStyles: {
      fillColor: [248, 250, 252],
      textColor: [30, 30, 30],
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 140 },
      1: { cellWidth: 40, halign: "right" },
    },
    styles: {
      fontSize: 10,
      cellPadding: 8,
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 150;

  // Payment instructions
  doc.setFillColor(248, 245, 255);
  doc.rect(14, finalY + 10, 182, 30, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(124, 58, 237);
  doc.text("Payment Instructions", 20, finalY + 22);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text("Please make payment by the due date shown above.", 20, finalY + 30);
  doc.text("Contact us if you have any questions about this invoice.", 20, finalY + 37);

  // Footer
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 275, 210, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Risely — userisely.com", 105, 284, { align: "center" });
  doc.text("Your AI Business Operating System", 105, 291, { align: "center" });

  // Save
  doc.save(`Invoice-${invoice.customer_name.replace(/\s+/g, "-")}-${invoice.id.slice(0, 8).toUpperCase()}.pdf`);
}